server:
  error:
    whitelabel:
      enabled: true

spring:

  application:
    name: backend-app

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-38357084.okta.com/oauth2/default
      client:
        registration:
          orange-money:
            authorization-grant-type: client_credentials
            client-id: a8b66e3a-c2eb-48c1-ad1c-c4b9b346a13f
            client-secret: db018580-b6a8-4158-bd7f-7ee3df4637e7
        provider:
          orange-money:
            token-uri: https://api.sandbox.orange-sonatel.com/oauth/token

  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/credit_db
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui

app:
  rest:
    client:
      om:
        url: https://api.sandbox.orange-sonatel.com
        retailer-pin-code: eXhOs4PRqNyFqaTDUZzIY6LUmwjnsN6/L6lPCn9cLRLxNEEGJrjfZWyZCmJa7xKB9+ILTzcu7+7OTPRgOC0O5v6TNrG0OI4ingb0+NUUV5ytaLz0lWzaJsQ7AFzB+tNYWoe++kikT1p+cUkFKeSeLsE/ieEXwHRK4GbkHPtVJcTZPebiJYwDyuSEbOjXUzvBvS8YT97hJR+E0WNsjrwKQunTQ3go6bQP1ceYTq0VJpa+TdSmaPSGc5W5+CS/CRtG9Z0GtCGQkdvf/5ZBpo81BwvzRyuMbhuES+FvC05xmDhYR9j4jc7vdLdQtIVL0L8YKVmSE0cBEurzLtey5w6hGg==


logging:
  level:
    com:
      engtechnologie:
        microcredit:
          payment:
            OrangeMoneyClient: debug